name: docs

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: '20'

    steps:
      - uses: actions/checkout@v4
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build documentation site
        run: npm run docs:build

      # 部署到腾讯云服务器
      - name: Deploy to Tencent Cloud server
        uses: easingthemes/ssh-deploy@v4.0.5
        env:
          #私钥
          SSH_PRIVATE_KEY: ${{ secrets.MY_TENCENT_SERVER_PRIVATE_SECRET_KEY }} #后面指定为该仓库配置的私钥
          ARGS: "-rltgoDzvO"
          SOURCE: 'docs/.vitepress/dist/'
          REMOTE_HOST: '43.153.21.203'
          REMOTE_USER: 'root'
          TARGET: '/home/blog/'
          SCRIPT_BEFORE: |
            rm -rf /home/blog/*
